version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://mongo:27017/math-solver
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "8001:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    restart: always
    ports:
      - "8002:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
